# Generated by Django 5.1.3 on 2024-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('datedecreation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('to do', 'A faire'), ('in progress', 'en cours'), ('done', 'terminer')], max_length=200)),
            ],
        ),
    ]
